import { Incident } from "@/types/incident";

export const incidents: Incident[] = [
  {
    id: "INC-2041",
    title: "Mobile Data Outage — Berlin-Brandenburg",
    service: "4G/5G Data",
    sev: "Critical",
    status: "Active",
    time: "14:02",
    sparkTrend: [2, 4, 3, 7, 8, 9, 8, 10],
    score: "9.1",
    duration: "1h 23m",
    assigned: "Oliver Schmidt",
    summary:
      "AI agent detected a complete 4G/5G data plane failure across the Berlin-Brandenburg region at 14:02 UTC. Root cause isolated to a BGP route withdrawal on the Frankfurt Gateway router following a firmware push at 13:58. Approximately 340,000 subscribers affected. Emergency rollback has been deployed; service restoration estimated within 15–20 minutes. Call volumes to support centre elevated by 312%. Correlated alarms: ALM-8821, ALM-8822, ALM-8830.",
    tags: ["4G Data", "5G NR", "Berlin-Brandenburg", "BGP", "Frankfurt Gateway"],
    evidence: [
      "ALM-8821 — BGP session drop on Frankfurt-GW-01",
      "ALM-8822 — Packet loss >98% on GGSN pool 4",
      "Downdetector score: 94/100 (critical)",
      "Support call volume +312% above baseline",
      "Firmware changelog: v12.4.1 → v12.4.2 (13:58 UTC)",
    ],
    timeline: [
      {
        time: "14:02",
        event: "Incident Detected",
        actor: "AI Agent — Auto-detection",
        color: "#ff3b5c",
        badge: "Detection",
        badgeBg: "rgba(255,59,92,0.15)",
      },
      {
        time: "14:05",
        event: "Escalated to NOC",
        actor: "PagerDuty Auto-escalation",
        color: "#ff8c00",
        badge: "Escalation",
        badgeBg: "rgba(255,140,0,0.15)",
      },
      {
        time: "14:09",
        event: "Assigned to Oliver Schmidt",
        actor: "NOC Shift Lead",
        color: "#38bdf8",
        badge: "Assignment",
        badgeBg: "rgba(56,189,248,0.15)",
      },
      {
        time: "14:14",
        event: "Reclassified to Critical",
        actor: "Oliver Schmidt",
        color: "#ff3b5c",
        badge: "Reclassification",
        badgeBg: "rgba(255,59,92,0.15)",
      },
      {
        time: "14:19",
        event: "Root Cause Identified — BGP withdrawal",
        actor: "AI Agent + Oliver Schmidt",
        color: "#E2008A",
        badge: "Root Cause",
        badgeBg: "rgba(226,0,138,0.15)",
      },
      {
        time: "14:25",
        event: "Fix Deployed — Firmware rollback initiated",
        actor: "Oliver Schmidt",
        color: "#00c896",
        badge: "Fix Deployed",
        badgeBg: "rgba(0,200,150,0.15)",
      },
    ],
  },
  {
    id: "INC-2039",
    title: "Voice Call Drop Rate Elevated",
    service: "Voice",
    sev: "Major",
    status: "In Progress",
    time: "13:47",
    sparkTrend: [3, 5, 6, 5, 7, 6, 8, 7],
    score: "6.4",
    duration: "1h 38m",
    assigned: "Jacob Meyer",
    summary:
      "Call drop rate on the VoLTE core has risen to 14.3% against an SLA baseline of 1.2%. AI agent correlates this to increased RTP packet loss on the IMS media plane, likely linked to a capacity breach on the media gateway cluster. Approximately 42,000 active calls impacted at peak. Jacob Meyer is performing gateway rebalancing. No emergency services calls affected.",
    tags: ["VoLTE", "IMS", "Media Gateway", "RTP"],
    evidence: [
      "CDR anomaly: drop rate 14.3% vs 1.2% baseline",
      "ALM-8815 — IMS media gateway CPU >95%",
      "RTP packet loss 8.7% on MGW cluster 3",
      "Downdetector voice score: 41/100",
    ],
    timeline: [
      {
        time: "13:47",
        event: "Incident Detected",
        actor: "AI Agent — CDR analytics",
        color: "#ff8c00",
        badge: "Detection",
        badgeBg: "rgba(255,140,0,0.15)",
      },
      {
        time: "13:52",
        event: "Assigned to Jacob Meyer",
        actor: "Auto-assignment rule",
        color: "#38bdf8",
        badge: "Assignment",
        badgeBg: "rgba(56,189,248,0.15)",
      },
      {
        time: "14:01",
        event: "Gateway rebalancing started",
        actor: "Jacob Meyer",
        color: "#E2008A",
        badge: "Mitigation",
        badgeBg: "rgba(226,0,138,0.15)",
      },
      {
        time: "14:18",
        event: "Drop rate stabilising at 6.1%",
        actor: "Jacob Meyer",
        color: "#f5c518",
        badge: "Progress",
        badgeBg: "rgba(245,197,24,0.15)",
      },
    ],
  },
  {
    id: "INC-2037",
    title: "SMS Delivery Delays — North Rhine-Westphalia",
    service: "SMS",
    sev: "Major",
    status: "In Progress",
    time: "12:30",
    sparkTrend: [1, 2, 4, 5, 4, 6, 5, 4],
    score: "5.8",
    duration: "2h 55m",
    assigned: "Anna Weber",
    summary:
      "SMS delivery latency in North Rhine-Westphalia has climbed to an average of 4m 12s, against an SLA target of under 30 seconds. The SMSC cluster handling NRW traffic is exhibiting queue depth overflow. AI agent traces the issue to a misconfigured rate limiter applied during the 11:00 UTC maintenance window. Anna Weber is coordinating with the Core team to revert the rate limiter configuration.",
    tags: ["SMSC", "North Rhine-Westphalia", "Rate Limiter", "Queue"],
    evidence: [
      "SMSC queue depth: 128,000 messages (normal: <5,000)",
      "ALM-8809 — SMSC-NRW-01 queue overflow",
      "Maintenance log: rate limiter config change 11:03 UTC",
      "Avg delivery latency: 4m 12s",
    ],
    timeline: [
      {
        time: "12:30",
        event: "Queue depth threshold breach",
        actor: "AI Agent — SMSC monitor",
        color: "#ff8c00",
        badge: "Detection",
        badgeBg: "rgba(255,140,0,0.15)",
      },
      {
        time: "12:38",
        event: "Assigned to Anna Weber",
        actor: "NOC Shift Lead",
        color: "#38bdf8",
        badge: "Assignment",
        badgeBg: "rgba(56,189,248,0.15)",
      },
      {
        time: "13:05",
        event: "Root cause identified — rate limiter",
        actor: "Anna Weber + AI Agent",
        color: "#E2008A",
        badge: "Root Cause",
        badgeBg: "rgba(226,0,138,0.15)",
      },
      {
        time: "13:44",
        event: "Config revert in progress",
        actor: "Anna Weber",
        color: "#f5c518",
        badge: "Mitigation",
        badgeBg: "rgba(245,197,24,0.15)",
      },
    ],
  },
  {
    id: "INC-2035",
    title: "Roaming Auth Failures — EU Partners",
    service: "Roaming",
    sev: "Critical",
    status: "Active",
    time: "11:15",
    sparkTrend: [5, 6, 8, 9, 8, 9, 10, 9],
    score: "8.7",
    duration: "4h 10m",
    assigned: "Unassigned",
    summary:
      "Authentication failures for inbound roaming subscribers from EU partner networks have reached 67% — a critical level that prevents international travellers from registering on the DT network. AI agent correlates the failure to an expired X.509 certificate on the DEA (Diameter Edge Agent) interconnect. Auto-escalation triggered after no engineer response within 15 minutes. Immediate certificate renewal required.",
    tags: ["Roaming", "Diameter", "DEA", "X.509", "EU Partners"],
    evidence: [
      "Diameter auth failure rate: 67%",
      "ALM-8801 — DEA certificate expiry",
      "Partner NOC alerts from Vodafone DE, Orange FR",
      "Auto-escalation sent at 11:30 UTC (no response)",
    ],
    timeline: [
      {
        time: "11:15",
        event: "Auth failure rate breach",
        actor: "AI Agent — Diameter probe",
        color: "#ff3b5c",
        badge: "Detection",
        badgeBg: "rgba(255,59,92,0.15)",
      },
      {
        time: "11:18",
        event: "Alert sent to On-Call engineer",
        actor: "PagerDuty",
        color: "#38bdf8",
        badge: "Alert",
        badgeBg: "rgba(56,189,248,0.15)",
      },
      {
        time: "11:33",
        event: "Auto-escalation — no response",
        actor: "PagerDuty Auto-escalation",
        color: "#ff3b5c",
        badge: "Escalation",
        badgeBg: "rgba(255,59,92,0.15)",
      },
      {
        time: "11:45",
        event: "Reclassified to Critical — unassigned",
        actor: "AI Agent",
        color: "#ff3b5c",
        badge: "Reclassification",
        badgeBg: "rgba(255,59,92,0.15)",
      },
    ],
  },
  {
    id: "INC-2033",
    title: "IoT Device Registration Lag",
    service: "IoT/M2M",
    sev: "Minor",
    status: "Monitoring",
    time: "10:58",
    sparkTrend: [6, 5, 4, 5, 3, 3, 2, 2],
    score: "3.2",
    duration: "4h 27m",
    assigned: "Stefan Bauer",
    summary:
      "IoT device registration latency on the M2M APN has been intermittently elevated, peaking at 12 seconds against a normal sub-2-second target. AI agent identifies the cause as a DNS resolver cache thrash following a nameserver config update. Stefan Bauer applied a TTL patch at 11:40 UTC. Metrics are improving and the incident is under active monitoring. No customer SLA breach at this time.",
    tags: ["IoT", "M2M", "APN", "DNS", "Registration"],
    evidence: [
      "Avg registration latency: 12s (normal <2s)",
      "DNS resolver cache miss rate: 89%",
      "Nameserver config change: 10:45 UTC",
      "TTL patch applied: 11:40 UTC",
    ],
    timeline: [
      {
        time: "10:58",
        event: "Registration latency threshold breach",
        actor: "AI Agent — IoT monitor",
        color: "#f5c518",
        badge: "Detection",
        badgeBg: "rgba(245,197,24,0.15)",
      },
      {
        time: "11:10",
        event: "Assigned to Stefan Bauer",
        actor: "Auto-assignment rule",
        color: "#38bdf8",
        badge: "Assignment",
        badgeBg: "rgba(56,189,248,0.15)",
      },
      {
        time: "11:40",
        event: "TTL patch applied — improving",
        actor: "Stefan Bauer",
        color: "#00c896",
        badge: "Mitigation",
        badgeBg: "rgba(0,200,150,0.15)",
      },
    ],
  },
  {
    id: "INC-2031",
    title: "Intermittent 5G NR Handover Fails",
    service: "5G NR",
    sev: "Major",
    status: "In Progress",
    time: "10:22",
    sparkTrend: [2, 3, 5, 7, 6, 8, 7, 6],
    score: "6.0",
    duration: "5h 03m",
    assigned: "Lena Hoffmann",
    summary:
      "5G NR inter-gNB handover failures are occurring at 8.4% across the Munich cluster, well above the 0.5% SLA threshold. AI agent pinpoints abnormal A3 event trigger parameters on a subset of gNBs following a SON policy update. Lena Hoffmann is performing RAN parameter tuning on the affected cells. A targeted rollback of the SON policy is planned if manual tuning does not resolve within 30 minutes.",
    tags: ["5G NR", "gNB", "Handover", "SON", "Munich"],
    evidence: [
      "Handover failure rate: 8.4% (SLA: <0.5%)",
      "ALM-8817 — A3 event abnormal trigger on gNB cluster 7",
      "SON policy update: 09:50 UTC",
      "Affected cells: 34 of 218 in Munich cluster",
    ],
    timeline: [
      {
        time: "10:22",
        event: "Handover failure rate breach",
        actor: "AI Agent — RAN analytics",
        color: "#ff8c00",
        badge: "Detection",
        badgeBg: "rgba(255,140,0,0.15)",
      },
      {
        time: "10:29",
        event: "Assigned to Lena Hoffmann",
        actor: "NOC Shift Lead",
        color: "#38bdf8",
        badge: "Assignment",
        badgeBg: "rgba(56,189,248,0.15)",
      },
      {
        time: "11:05",
        event: "RAN parameter tuning started",
        actor: "Lena Hoffmann",
        color: "#E2008A",
        badge: "Mitigation",
        badgeBg: "rgba(226,0,138,0.15)",
      },
      {
        time: "14:10",
        event: "Partial recovery — 22 of 34 cells restored",
        actor: "Lena Hoffmann",
        color: "#f5c518",
        badge: "Progress",
        badgeBg: "rgba(245,197,24,0.15)",
      },
    ],
  },
  {
    id: "INC-2028",
    title: "Core Network Latency Spike",
    service: "Core/IMS",
    sev: "Critical",
    status: "Active",
    time: "09:44",
    sparkTrend: [3, 5, 7, 8, 9, 10, 9, 10],
    score: "8.9",
    duration: "5h 41m",
    assigned: "Oliver Schmidt",
    summary:
      "Signalling plane latency on the IMS core has spiked to 420ms — 14x the normal operating level. AI agent identifies a memory leak in the P-CSCF process pool causing cascading timeouts. CTO has been notified. Emergency services (112) call routing has been isolated to a dedicated redundant path to maintain critical service continuity. Oliver Schmidt is coordinating a controlled P-CSCF process restart sequence.",
    tags: ["IMS", "P-CSCF", "Signalling", "Core", "Emergency Services"],
    evidence: [
      "IMS signalling latency: 420ms (normal <30ms)",
      "ALM-8800 — P-CSCF memory utilisation 99.8%",
      "ALM-8803 — SIP transaction timeout rate 34%",
      "CTO escalation: 10:15 UTC",
      "Emergency services path isolated: 10:22 UTC",
    ],
    timeline: [
      {
        time: "09:44",
        event: "Latency spike detected",
        actor: "AI Agent — IMS probe",
        color: "#ff3b5c",
        badge: "Detection",
        badgeBg: "rgba(255,59,92,0.15)",
      },
      {
        time: "09:50",
        event: "Assigned to Oliver Schmidt",
        actor: "Auto-assignment (Critical SLA)",
        color: "#38bdf8",
        badge: "Assignment",
        badgeBg: "rgba(56,189,248,0.15)",
      },
      {
        time: "10:15",
        event: "CTO notified — emergency services flag raised",
        actor: "Oliver Schmidt",
        color: "#ff3b5c",
        badge: "Escalation",
        badgeBg: "rgba(255,59,92,0.15)",
      },
      {
        time: "10:22",
        event: "Emergency services isolated to redundant path",
        actor: "Oliver Schmidt + NOC",
        color: "#E2008A",
        badge: "Mitigation",
        badgeBg: "rgba(226,0,138,0.15)",
      },
      {
        time: "14:10",
        event: "P-CSCF restart sequence initiated",
        actor: "Oliver Schmidt",
        color: "#f5c518",
        badge: "In Progress",
        badgeBg: "rgba(245,197,24,0.15)",
      },
    ],
  },
  {
    id: "INC-2025",
    title: "Downdetector Score Threshold Breach",
    service: "User Reports",
    sev: "Minor",
    status: "Monitoring",
    time: "09:10",
    sparkTrend: [1, 2, 3, 4, 4, 3, 3, 2],
    score: "2.8",
    duration: "6h 15m",
    assigned: "Auto-monitor",
    summary:
      "Downdetector aggregated user report score exceeded the elevated threshold of 50/100, reaching a peak of 62/100. AI agent auto-correlated this user-reported signal to INC-2028 (Core Network Latency Spike), confirming that perceived service degradation is a downstream effect of IMS signalling delays. No independent network fault identified. Monitor will auto-close upon INC-2028 resolution.",
    tags: ["User Reports", "Downdetector", "Social Signal", "INC-2028"],
    evidence: [
      "Downdetector score: 62/100 (threshold: 50/100)",
      "Correlation confidence: 94% with INC-2028",
      "Twitter/X mentions: 1,240 in 1hr window",
      "Auto-monitor: will close with INC-2028",
    ],
    timeline: [
      {
        time: "09:10",
        event: "Downdetector threshold breach",
        actor: "AI Agent — Social signal monitor",
        color: "#f5c518",
        badge: "Detection",
        badgeBg: "rgba(245,197,24,0.15)",
      },
      {
        time: "09:18",
        event: "Auto-correlated to INC-2028",
        actor: "AI Agent — Correlation engine",
        color: "#E2008A",
        badge: "Correlation",
        badgeBg: "rgba(226,0,138,0.15)",
      },
      {
        time: "09:25",
        event: "Auto-monitor assigned — no engineer needed",
        actor: "AI Agent",
        color: "#00c896",
        badge: "Auto-Monitor",
        badgeBg: "rgba(0,200,150,0.15)",
      },
    ],
  },
];

export const volumeData = [
  { hour: "00:00", Critical: 0, Major: 1, Minor: 2 },
  { hour: "02:00", Critical: 0, Major: 1, Minor: 1 },
  { hour: "04:00", Critical: 1, Major: 2, Minor: 2 },
  { hour: "06:00", Critical: 1, Major: 2, Minor: 3 },
  { hour: "08:00", Critical: 2, Major: 3, Minor: 4 },
  { hour: "10:00", Critical: 3, Major: 5, Minor: 4 },
  { hour: "12:00", Critical: 2, Major: 4, Minor: 3 },
  { hour: "14:00", Critical: 3, Major: 6, Minor: 5 },
  { hour: "16:00", Critical: 2, Major: 4, Minor: 4 },
  { hour: "18:00", Critical: 1, Major: 3, Minor: 3 },
  { hour: "20:00", Critical: 1, Major: 2, Minor: 2 },
  { hour: "22:00", Critical: 0, Major: 1, Minor: 1 },
];

export const callVolumeData = [
  { hour: "09", volume: 210 },
  { hour: "10", volume: 245 },
  { hour: "11", volume: 280 },
  { hour: "12", volume: 260 },
  { hour: "13", volume: 310 },
  { hour: "14", volume: 321 },
];

export const alarmTableData = [
  { alarm: "ALM-8821", duration: "1h 23m", status: "Critical" },
  { alarm: "ALM-8817", duration: "5h 03m", status: "Major" },
  { alarm: "ALM-8815", duration: "1h 38m", status: "Major" },
  { alarm: "ALM-8809", duration: "2h 55m", status: "Major" },
  { alarm: "ALM-8803", duration: "5h 41m", status: "Critical" },
];

export const alarmChartData = [
  { t: "09:00", critical: 2, major: 3 },
  { t: "10:00", critical: 4, major: 5 },
  { t: "11:00", critical: 3, major: 6 },
  { t: "12:00", critical: 5, major: 7 },
  { t: "13:00", critical: 7, major: 8 },
  { t: "14:00", critical: 8, major: 9 },
];

export const downDetectorData = [
  { time: "09:00", score: 28 },
  { time: "10:00", score: 38 },
  { time: "11:00", score: 45 },
  { time: "12:00", score: 55 },
  { time: "13:00", score: 60 },
  { time: "14:00", score: 62 },
];

export const callComposedData = [
  { hour: "09", volume: 210, trend: 215 },
  { hour: "10", volume: 245, trend: 240 },
  { hour: "11", volume: 280, trend: 270 },
  { hour: "12", volume: 260, trend: 265 },
  { hour: "13", volume: 310, trend: 300 },
  { hour: "14", volume: 321, trend: 315 },
];

export const ticketData = [
  { ticket: "TKT-1041", summary: "BGP route withdrawal — Frankfurt GW", status: "In Progress" },
  { ticket: "TKT-1039", summary: "VoLTE media gateway rebalance", status: "In Progress" },
  { ticket: "TKT-1037", summary: "SMSC rate limiter revert — NRW", status: "To Do" },
  { ticket: "TKT-1035", summary: "DEA certificate renewal", status: "To Do" },
  { ticket: "TKT-1033", summary: "DNS TTL patch — IoT APN", status: "Done" },
  { ticket: "TKT-1031", summary: "RAN parameter tuning — Munich", status: "In Progress" },
];
