import { HistoricalIncident } from "@/types/incident";

export const historyIncidents: HistoricalIncident[] = [
  {
    id: "INC-1905",
    title: "DNS Resolver Cache Thrash — IoT APN",
    service: "IoT/M2M",
    sev: "Minor",
    status: "Resolved",
    date: "2025-12-01",
    time: "10:15",
    endDate: "2025-12-01",
    resolvedAt: "11:00",
    duration: "0h 45m",
    assigned: "Stefan Bauer",
    classification: "DNS Issue",
    score: "2.1",
    sparkTrend: [1, 2, 2, 3, 2, 2, 1, 1],
    summary: "IoT APN DNS resolver entered a cache thrash loop following a nameserver TTL update. Stefan Bauer applied a TTL patch restoring sub-2s registration latency.",
    tags: ["IoT", "M2M", "DNS", "APN"],
    evidence: ["DNS cache miss rate: 87%", "Nameserver TTL change: 10:00 UTC"],
    timeline: [
      { time: "10:15", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "10:28", event: "Assigned to Stefan Bauer", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "11:00", event: "Resolved — TTL patch applied", actor: "Stefan Bauer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1907",
    title: "SMSC Rate Limiter Misconfiguration — NRW",
    service: "SMS",
    sev: "Major",
    status: "Resolved",
    date: "2025-12-04",
    time: "08:30",
    endDate: "2025-12-04",
    resolvedAt: "11:15",
    duration: "2h 45m",
    assigned: "Anna Weber",
    classification: "Config Error",
    score: "5.2",
    sparkTrend: [1, 3, 5, 6, 5, 4, 3, 2],
    summary: "SMSC delivery latency elevated across NRW region due to a misconfigured rate limiter applied during a maintenance window. Anna Weber reverted the config and cleared the message queue.",
    tags: ["SMSC", "NRW", "Rate Limiter", "Queue"],
    evidence: ["SMSC queue depth: 54,000 (normal <5,000)", "Rate limiter change: 08:15 UTC"],
    timeline: [
      { time: "08:30", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "08:42", event: "Assigned to Anna Weber", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "09:55", event: "Root cause identified", actor: "Anna Weber", color: "#E2008A", badge: "Root Cause", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "11:15", event: "Resolved — config reverted", actor: "Anna Weber", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1909",
    title: "BGP Route Withdrawal — Hamburg Gateway",
    service: "4G/5G Data",
    sev: "Critical",
    status: "Resolved",
    date: "2025-12-09",
    time: "13:00",
    endDate: "2025-12-09",
    resolvedAt: "15:30",
    duration: "2h 30m",
    assigned: "Oliver Schmidt",
    classification: "BGP Failure",
    score: "8.6",
    sparkTrend: [2, 4, 7, 9, 10, 9, 6, 3],
    summary: "BGP route withdrawal on Hamburg-GW-02 caused a complete 4G/5G data plane failure across the Hamburg metro region. Emergency firmware rollback executed by Oliver Schmidt within 2h 30m.",
    tags: ["4G Data", "5G NR", "BGP", "Hamburg Gateway"],
    evidence: ["BGP session drop on Hamburg-GW-02", "Packet loss >97%", "Support call volume +278%"],
    timeline: [
      { time: "13:00", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "13:08", event: "Assigned to Oliver Schmidt", actor: "Auto-escalation (Critical)", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "13:42", event: "Root cause identified — BGP", actor: "Oliver Schmidt", color: "#E2008A", badge: "Root Cause", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "15:30", event: "Resolved — firmware rollback", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1911",
    title: "VoLTE Media Gateway Capacity Breach",
    service: "Voice",
    sev: "Major",
    status: "Resolved",
    date: "2025-12-11",
    time: "11:20",
    endDate: "2025-12-11",
    resolvedAt: "13:50",
    duration: "2h 30m",
    assigned: "Jacob Meyer",
    classification: "Capacity Breach",
    score: "6.1",
    sparkTrend: [2, 3, 5, 6, 7, 6, 4, 2],
    summary: "VoLTE media gateway CPU reached 97% causing elevated call drop rates across the IMS core. Jacob Meyer completed gateway rebalancing and scaled out an additional media gateway node.",
    tags: ["VoLTE", "IMS", "Media Gateway", "Capacity"],
    evidence: ["Media gateway CPU: 97%", "Call drop rate: 11.2% vs 1.2% SLA"],
    timeline: [
      { time: "11:20", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "11:33", event: "Assigned to Jacob Meyer", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "13:50", event: "Resolved — gateway rebalanced", actor: "Jacob Meyer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1913",
    title: "Roaming Certificate Expiry — EU Partners",
    service: "Roaming",
    sev: "Minor",
    status: "Resolved",
    date: "2025-12-14",
    time: "09:05",
    endDate: "2025-12-14",
    resolvedAt: "09:55",
    duration: "0h 50m",
    assigned: "Lena Hoffmann",
    classification: "Certificate Expiry",
    score: "3.0",
    sparkTrend: [1, 2, 3, 4, 3, 2, 2, 1],
    summary: "Minor DEA certificate pre-expiry alert triggered for a low-traffic EU partner interconnect. Lena Hoffmann renewed the certificate before service impact occurred.",
    tags: ["Roaming", "Diameter", "DEA", "X.509"],
    evidence: ["DEA cert expiry warning: 24h remaining", "Affected partners: T-Mobile AT"],
    timeline: [
      { time: "09:05", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "09:18", event: "Assigned to Lena Hoffmann", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "09:55", event: "Resolved — certificate renewed", actor: "Lena Hoffmann", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1915",
    title: "5G NR gNB Software Update Failure — Dresden",
    service: "5G NR",
    sev: "Major",
    status: "Resolved",
    date: "2025-12-17",
    time: "14:30",
    endDate: "2025-12-17",
    resolvedAt: "17:00",
    duration: "2h 30m",
    assigned: "Kai Fischer",
    classification: "Software Bug",
    score: "5.7",
    sparkTrend: [1, 2, 4, 5, 6, 5, 3, 2],
    summary: "Software update rollout to gNB cluster in Dresden caused abnormal A3 handover event triggers. Kai Fischer halted the rollout and rolled back 28 affected cells.",
    tags: ["5G NR", "gNB", "Handover", "Dresden", "Software Update"],
    evidence: ["Handover failure rate: 7.1% vs 0.5% SLA", "gNB software version mismatch detected"],
    timeline: [
      { time: "14:30", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "14:43", event: "Assigned to Kai Fischer", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "17:00", event: "Resolved — rollback complete", actor: "Kai Fischer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1917",
    title: "IMS Signalling Overload — Core West",
    service: "Core/IMS",
    sev: "Minor",
    status: "Resolved",
    date: "2025-12-19",
    time: "16:10",
    endDate: "2025-12-19",
    resolvedAt: "17:05",
    duration: "0h 55m",
    assigned: "Mia Becker",
    classification: "Network Congestion",
    score: "2.9",
    sparkTrend: [1, 1, 2, 3, 3, 2, 2, 1],
    summary: "Transient IMS signalling load spike on Core West caused minor SIP timeout elevations. Mia Becker identified a batch job consuming disproportionate signalling capacity and rescheduled it.",
    tags: ["IMS", "SIP", "Signalling", "Core West"],
    evidence: ["SIP transaction timeout: 3.2% vs 0.5% baseline", "Batch job scheduler conflict identified"],
    timeline: [
      { time: "16:10", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "16:22", event: "Assigned to Mia Becker", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "17:05", event: "Resolved — batch job rescheduled", actor: "Mia Becker", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1919",
    title: "P-CSCF Hardware Failure — Primary Node",
    service: "Core/IMS",
    sev: "Critical",
    status: "Resolved",
    date: "2025-12-23",
    time: "10:00",
    endDate: "2025-12-23",
    resolvedAt: "16:30",
    duration: "6h 30m",
    assigned: "Oliver Schmidt",
    classification: "Hardware Fault",
    score: "9.0",
    sparkTrend: [3, 5, 8, 10, 10, 9, 7, 4],
    summary: "Primary P-CSCF node suffered a dual NIC failure causing IMS signalling plane degradation. Oliver Schmidt coordinated emergency failover to the redundant P-CSCF and replacement hardware procurement.",
    tags: ["IMS", "P-CSCF", "Hardware", "NIC", "Failover"],
    evidence: ["P-CSCF NIC-A and NIC-B failure", "IMS latency: 390ms (normal <30ms)", "Emergency services isolated to redundant path"],
    timeline: [
      { time: "10:00", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "10:06", event: "Assigned to Oliver Schmidt", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "10:25", event: "Emergency services isolated", actor: "Oliver Schmidt", color: "#E2008A", badge: "Mitigation", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "16:30", event: "Resolved — failover complete", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1921",
    title: "4G RAN Firmware Bug — Munich Cluster",
    service: "4G/5G Data",
    sev: "Major",
    status: "Resolved",
    date: "2025-12-30",
    time: "09:15",
    endDate: "2025-12-30",
    resolvedAt: "11:00",
    duration: "1h 45m",
    assigned: "Oliver Schmidt",
    classification: "Firmware Bug",
    score: "5.5",
    sparkTrend: [1, 3, 5, 6, 5, 4, 3, 2],
    summary: "Firmware regression in v14.2.1 caused abnormal PDCP retransmission rates across the Munich 4G RAN cluster. Oliver Schmidt deployed the hotfix patch v14.2.2 to all affected eNBs.",
    tags: ["4G", "RAN", "eNB", "Firmware", "Munich"],
    evidence: ["PDCP retransmission rate: 18% vs 2% baseline", "Firmware v14.2.1 deployed: 09:00 UTC"],
    timeline: [
      { time: "09:15", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "09:28", event: "Assigned to Oliver Schmidt", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "11:00", event: "Resolved — hotfix v14.2.2 deployed", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1923",
    title: "Planned Maintenance — SMSC Queue Disruption",
    service: "SMS",
    sev: "Minor",
    status: "Resolved",
    date: "2026-01-02",
    time: "14:00",
    endDate: "2026-01-02",
    resolvedAt: "14:40",
    duration: "0h 40m",
    assigned: "Anna Weber",
    classification: "Maintenance Window",
    score: "1.8",
    sparkTrend: [1, 1, 2, 2, 2, 1, 1, 1],
    summary: "Brief SMSC disruption during scheduled maintenance window. Message queue briefly elevated above threshold before auto-draining. No SLA breach.",
    tags: ["SMSC", "Maintenance", "SMS Queue"],
    evidence: ["SMSC queue: 8,200 messages (threshold: 5,000)", "Planned maintenance window: 14:00–15:00 UTC"],
    timeline: [
      { time: "14:00", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "14:40", event: "Resolved — queue drained", actor: "Anna Weber", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1925",
    title: "VoLTE Gateway Hardware Fault — Cologne",
    service: "Voice",
    sev: "Critical",
    status: "Resolved",
    date: "2026-01-06",
    time: "08:45",
    endDate: "2026-01-06",
    resolvedAt: "12:15",
    duration: "3h 30m",
    assigned: "Jacob Meyer",
    classification: "Hardware Fault",
    score: "8.3",
    sparkTrend: [3, 5, 7, 9, 9, 8, 6, 3],
    summary: "VoLTE gateway in Cologne suffered a power supply unit failure causing loss of 34% of regional voice capacity. Jacob Meyer coordinated emergency failover and replacement PSU installation.",
    tags: ["VoLTE", "Voice", "Cologne", "PSU", "Hardware"],
    evidence: ["PSU failure alarm: COL-MGW-02", "Voice capacity loss: 34%", "Emergency services on backup path"],
    timeline: [
      { time: "08:45", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "08:52", event: "Assigned to Jacob Meyer", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "09:30", event: "Failover completed", actor: "Jacob Meyer", color: "#E2008A", badge: "Mitigation", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "12:15", event: "Resolved — PSU replaced", actor: "Jacob Meyer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1927",
    title: "Roaming BGP Session Drop — Vodafone DE",
    service: "Roaming",
    sev: "Major",
    status: "Resolved",
    date: "2026-01-07",
    time: "10:30",
    endDate: "2026-01-07",
    resolvedAt: "13:00",
    duration: "2h 30m",
    assigned: "Lena Hoffmann",
    classification: "BGP Failure",
    score: "6.4",
    sparkTrend: [2, 3, 5, 6, 7, 6, 4, 2],
    summary: "BGP session between the DT Diameter Edge Agent and Vodafone DE peering point dropped, blocking inbound roaming authentication. Lena Hoffmann restored the session and validated partner reconnection.",
    tags: ["Roaming", "BGP", "Vodafone DE", "DEA"],
    evidence: ["BGP session drop: DEA-peer-VDF-01", "Roaming auth failure: 41%"],
    timeline: [
      { time: "10:30", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "10:44", event: "Assigned to Lena Hoffmann", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "13:00", event: "Resolved — BGP session restored", actor: "Lena Hoffmann", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1929",
    title: "5G NR SON Policy Config Error — Stuttgart",
    service: "5G NR",
    sev: "Major",
    status: "Resolved",
    date: "2026-01-08",
    time: "13:15",
    endDate: "2026-01-08",
    resolvedAt: "15:45",
    duration: "2h 30m",
    assigned: "Kai Fischer",
    classification: "Config Error",
    score: "5.9",
    sparkTrend: [1, 2, 4, 5, 6, 5, 3, 2],
    summary: "Incorrect SON policy parameters applied to Stuttgart gNB cluster caused abnormal cell reselection behaviour. Kai Fischer reverted the SON policy and verified cluster stability.",
    tags: ["5G NR", "gNB", "SON", "Stuttgart", "Config"],
    evidence: ["Cell reselection rate: 22% vs 4% baseline", "SON policy change: 13:00 UTC"],
    timeline: [
      { time: "13:15", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "13:29", event: "Assigned to Kai Fischer", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "15:45", event: "Resolved — SON policy reverted", actor: "Kai Fischer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1931",
    title: "IoT DNS TTL Update — M2M APN",
    service: "IoT/M2M",
    sev: "Minor",
    status: "Resolved",
    date: "2026-01-09",
    time: "09:30",
    endDate: "2026-01-09",
    resolvedAt: "10:20",
    duration: "0h 50m",
    assigned: "Stefan Bauer",
    classification: "DNS Issue",
    score: "2.3",
    sparkTrend: [1, 1, 2, 3, 2, 2, 1, 1],
    summary: "M2M APN DNS TTL configuration change caused transient registration delays. Stefan Bauer restored previous TTL values.",
    tags: ["IoT", "M2M", "DNS", "APN"],
    evidence: ["Registration latency peak: 9s", "DNS TTL change detected: 09:15 UTC"],
    timeline: [
      { time: "09:30", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "10:20", event: "Resolved", actor: "Stefan Bauer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1933",
    title: "P-CSCF Software Memory Leak — Core South",
    service: "Core/IMS",
    sev: "Critical",
    status: "Resolved",
    date: "2026-01-13",
    time: "11:00",
    endDate: "2026-01-13",
    resolvedAt: "17:30",
    duration: "6h 30m",
    assigned: "Oliver Schmidt",
    classification: "Software Bug",
    score: "9.2",
    sparkTrend: [4, 6, 8, 10, 10, 9, 7, 4],
    summary: "Recurring memory leak in P-CSCF process pool caused cascading IMS signalling timeouts on Core South. Oliver Schmidt coordinated a controlled process restart sequence while maintaining emergency service continuity.",
    tags: ["IMS", "P-CSCF", "Memory Leak", "Core South", "SIP"],
    evidence: ["P-CSCF memory: 99.6%", "SIP timeout rate: 29%", "CTO escalated: 12:30 UTC"],
    timeline: [
      { time: "11:00", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "11:08", event: "Assigned to Oliver Schmidt", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "12:30", event: "CTO escalated", actor: "Oliver Schmidt", color: "#ff3b5c", badge: "Escalation", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "17:30", event: "Resolved — process restart complete", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1935",
    title: "4G Data Capacity Breach — Berlin-Mitte",
    service: "4G/5G Data",
    sev: "Major",
    status: "Resolved",
    date: "2026-01-15",
    time: "12:00",
    endDate: "2026-01-15",
    resolvedAt: "14:30",
    duration: "2h 30m",
    assigned: "Mia Becker",
    classification: "Capacity Breach",
    score: "5.8",
    sparkTrend: [2, 3, 5, 6, 7, 5, 4, 2],
    summary: "Unexpected traffic surge in Berlin-Mitte caused GGSN pool capacity breach. Mia Becker activated load-shedding and provisioned an additional GGSN node within SLA window.",
    tags: ["4G", "GGSN", "Capacity", "Berlin-Mitte"],
    evidence: ["GGSN pool utilisation: 98%", "Traffic spike: +180% above baseline"],
    timeline: [
      { time: "12:00", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "12:14", event: "Assigned to Mia Becker", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "14:30", event: "Resolved — additional node provisioned", actor: "Mia Becker", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1937",
    title: "SMS Gateway Network Congestion — Bavaria",
    service: "SMS",
    sev: "Minor",
    status: "Resolved",
    date: "2026-01-17",
    time: "10:10",
    endDate: "2026-01-17",
    resolvedAt: "10:55",
    duration: "0h 45m",
    assigned: "Anna Weber",
    classification: "Network Congestion",
    score: "2.5",
    sparkTrend: [1, 2, 3, 3, 3, 2, 2, 1],
    summary: "Transient network congestion on the Bavaria SMS GW segment elevated delivery latency. Anna Weber identified and resolved a QoS misclassification on the interconnect.",
    tags: ["SMS", "Gateway", "QoS", "Bavaria"],
    evidence: ["SMS delivery latency: 45s vs 30s SLA", "QoS misclassification on SMG-BAV-01"],
    timeline: [
      { time: "10:10", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "10:55", event: "Resolved — QoS corrected", actor: "Anna Weber", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1939",
    title: "BGP Peering Failure — Voice Core Frankfurt",
    service: "Voice",
    sev: "Critical",
    status: "Resolved",
    date: "2026-01-20",
    time: "09:00",
    endDate: "2026-01-20",
    resolvedAt: "14:00",
    duration: "5h 00m",
    assigned: "Jacob Meyer",
    classification: "BGP Failure",
    score: "8.8",
    sparkTrend: [3, 5, 8, 10, 10, 9, 7, 4],
    summary: "BGP peering failure on the Frankfurt voice core caused loss of inter-carrier voice routing for 22% of outbound calls. Jacob Meyer isolated affected paths and restored peering within 5 hours.",
    tags: ["Voice", "BGP", "Frankfurt", "Inter-carrier"],
    evidence: ["BGP peer drop: FRA-VC-PEER-01", "Outbound call failure: 22%", "Partner NOC alerts from 4 operators"],
    timeline: [
      { time: "09:00", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "09:09", event: "Assigned to Jacob Meyer", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "11:30", event: "Partial restoration — alternate path", actor: "Jacob Meyer", color: "#E2008A", badge: "Mitigation", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "14:00", event: "Resolved — full BGP peering restored", actor: "Jacob Meyer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1941",
    title: "5G NR Firmware Regression — Düsseldorf",
    service: "5G NR",
    sev: "Major",
    status: "Resolved",
    date: "2026-01-21",
    time: "13:30",
    endDate: "2026-01-21",
    resolvedAt: "16:00",
    duration: "2h 30m",
    assigned: "Lena Hoffmann",
    classification: "Firmware Bug",
    score: "5.6",
    sparkTrend: [1, 2, 4, 5, 6, 5, 4, 2],
    summary: "Firmware regression in gNB v3.8.1 caused PDSCH scheduling inefficiencies across the Düsseldorf 5G cluster, degrading peak throughput by 38%. Lena Hoffmann rolled back to v3.7.9.",
    tags: ["5G NR", "gNB", "Firmware", "Düsseldorf", "PDSCH"],
    evidence: ["Peak throughput degradation: -38%", "Firmware v3.8.1 deployed: 13:00 UTC"],
    timeline: [
      { time: "13:30", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "13:44", event: "Assigned to Lena Hoffmann", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "16:00", event: "Resolved — rolled back to v3.7.9", actor: "Lena Hoffmann", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1943",
    title: "Roaming Certificate Expiry — Orange FR",
    service: "Roaming",
    sev: "Major",
    status: "Resolved",
    date: "2026-01-22",
    time: "11:15",
    endDate: "2026-01-22",
    resolvedAt: "13:45",
    duration: "2h 30m",
    assigned: "Kai Fischer",
    classification: "Certificate Expiry",
    score: "6.0",
    sparkTrend: [2, 3, 5, 6, 6, 5, 3, 2],
    summary: "X.509 certificate on the Orange FR DEA interconnect expired without auto-renewal due to a misconfigured renewal job. Kai Fischer manually renewed the certificate and corrected the renewal scheduler.",
    tags: ["Roaming", "DEA", "X.509", "Orange FR", "Certificate"],
    evidence: ["DEA cert expired: DEA-OFR-01", "Auth failure rate: 58% for Orange FR subscribers"],
    timeline: [
      { time: "11:15", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "11:28", event: "Assigned to Kai Fischer", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "13:45", event: "Resolved — certificate renewed", actor: "Kai Fischer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1945",
    title: "IoT M2M APN Config Drift",
    service: "IoT/M2M",
    sev: "Minor",
    status: "Resolved",
    date: "2026-01-24",
    time: "08:40",
    endDate: "2026-01-24",
    resolvedAt: "09:30",
    duration: "0h 50m",
    assigned: "Stefan Bauer",
    classification: "Config Error",
    score: "2.2",
    sparkTrend: [1, 1, 2, 2, 2, 2, 1, 1],
    summary: "Configuration drift on the M2M APN gateway caused a subset of IoT devices to use a deprecated authentication method. Stefan Bauer pushed a config correction.",
    tags: ["IoT", "M2M", "APN", "Config", "Authentication"],
    evidence: ["Deprecated auth method usage: 8% of devices", "Config drift detected vs baseline"],
    timeline: [
      { time: "08:40", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "09:30", event: "Resolved — config corrected", actor: "Stefan Bauer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1947",
    title: "Core IMS Hardware Failure — Frankfurt Primary",
    service: "Core/IMS",
    sev: "Critical",
    status: "Resolved",
    date: "2026-01-27",
    time: "14:00",
    endDate: "2026-01-27",
    resolvedAt: "20:00",
    duration: "6h 00m",
    assigned: "Oliver Schmidt",
    classification: "Hardware Fault",
    score: "9.4",
    sparkTrend: [4, 6, 8, 10, 10, 9, 7, 5],
    summary: "Dual SSD failure on the primary IMS database node caused a complete loss of active subscriber session state. Oliver Schmidt coordinated emergency failover and session state reconstruction from the standby node.",
    tags: ["IMS", "Core", "SSD", "Database", "Frankfurt", "Failover"],
    evidence: ["SSD failure: IMS-DB-FRA-01 (RAID degraded)", "Active session loss: 1.4M subscribers", "CTO and CISO notified"],
    timeline: [
      { time: "14:00", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "14:06", event: "Assigned to Oliver Schmidt", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "14:45", event: "CTO/CISO notified", actor: "Oliver Schmidt", color: "#ff3b5c", badge: "Escalation", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "17:00", event: "Standby failover completed", actor: "Oliver Schmidt", color: "#E2008A", badge: "Mitigation", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "20:00", event: "Resolved — session state reconstructed", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1949",
    title: "4G Data BGP Flap — Leipzig Gateway",
    service: "4G/5G Data",
    sev: "Major",
    status: "Resolved",
    date: "2026-01-28",
    time: "10:15",
    endDate: "2026-01-28",
    resolvedAt: "12:00",
    duration: "1h 45m",
    assigned: "Mia Becker",
    classification: "BGP Failure",
    score: "5.9",
    sparkTrend: [2, 3, 5, 6, 6, 5, 4, 2],
    summary: "BGP flapping on the Leipzig Gateway caused intermittent 4G data plane drops affecting 80,000 subscribers. Mia Becker stabilised the session by adjusting route dampening parameters.",
    tags: ["4G Data", "BGP", "Leipzig Gateway"],
    evidence: ["BGP flap count: 14 in 20 minutes", "4G data interruption: 80K subscribers"],
    timeline: [
      { time: "10:15", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "10:29", event: "Assigned to Mia Becker", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "12:00", event: "Resolved — route dampening adjusted", actor: "Mia Becker", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1951",
    title: "SMSC DNS Resolution Failure — Düsseldorf",
    service: "SMS",
    sev: "Major",
    status: "Resolved",
    date: "2026-01-28",
    time: "09:00",
    endDate: "2026-01-28",
    resolvedAt: "11:30",
    duration: "2h 30m",
    assigned: "Anna Weber",
    classification: "DNS Issue",
    score: "5.4",
    sparkTrend: [2, 3, 4, 5, 6, 5, 4, 2],
    summary: "SMSC cluster in Düsseldorf lost DNS resolution to the HLR following a resolver misconfiguration. Anna Weber restored resolution and cleared the resulting message queue backlog.",
    tags: ["SMSC", "DNS", "HLR", "Düsseldorf"],
    evidence: ["DNS resolution failure: SMSC-DUS-02 → HLR", "Queue depth: 22,000 messages"],
    timeline: [
      { time: "09:00", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "09:14", event: "Assigned to Anna Weber", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "11:30", event: "Resolved — DNS restored, queue cleared", actor: "Anna Weber", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1953",
    title: "Voice Capacity Breach — Ruhr Area",
    service: "Voice",
    sev: "Critical",
    status: "Resolved",
    date: "2026-02-03",
    time: "11:30",
    endDate: "2026-02-03",
    resolvedAt: "16:00",
    duration: "4h 30m",
    assigned: "Jacob Meyer",
    classification: "Capacity Breach",
    score: "8.5",
    sparkTrend: [3, 5, 7, 9, 10, 9, 7, 4],
    summary: "Unexpected mass call event in the Ruhr area exceeded voice gateway capacity by 240%. Jacob Meyer activated emergency capacity burst mode and routed overflow to neighbouring clusters.",
    tags: ["Voice", "Capacity", "Ruhr", "Emergency Burst", "VoLTE"],
    evidence: ["Voice gateway utilisation: 340%", "Call rejection rate: 31%", "Mass calling event confirmed by media monitoring"],
    timeline: [
      { time: "11:30", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "11:38", event: "Assigned to Jacob Meyer", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "12:15", event: "Emergency burst mode activated", actor: "Jacob Meyer", color: "#E2008A", badge: "Mitigation", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "16:00", event: "Resolved — capacity normalised", actor: "Jacob Meyer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1955",
    title: "5G NR Software Update Issue — Nuremberg",
    service: "5G NR",
    sev: "Major",
    status: "Resolved",
    date: "2026-02-04",
    time: "09:00",
    endDate: "2026-02-04",
    resolvedAt: "11:30",
    duration: "2h 30m",
    assigned: "Lena Hoffmann",
    classification: "Software Bug",
    score: "5.7",
    sparkTrend: [1, 2, 4, 5, 6, 5, 4, 2],
    summary: "Software update to gNB v3.9.0 introduced a beam management regression across the Nuremberg 5G cluster. Lena Hoffmann halted the rollout and rolled back affected cells.",
    tags: ["5G NR", "gNB", "Beam Management", "Nuremberg"],
    evidence: ["Beam failure rate: 12.4% vs 0.8% baseline", "gNB v3.9.0 rollout: 08:45 UTC"],
    timeline: [
      { time: "09:00", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "09:12", event: "Assigned to Lena Hoffmann", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "11:30", event: "Resolved — rollback complete", actor: "Lena Hoffmann", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1957",
    title: "BGP Route Withdrawal — Leipzig-Dresden Corridor",
    service: "4G/5G Data",
    sev: "Critical",
    status: "Resolved",
    date: "2026-02-04",
    time: "13:15",
    endDate: "2026-02-04",
    resolvedAt: "16:30",
    duration: "3h 15m",
    assigned: "Oliver Schmidt",
    classification: "BGP Failure",
    score: "8.9",
    sparkTrend: [3, 5, 8, 10, 10, 9, 7, 4],
    summary: "BGP route withdrawal on the Leipzig-Dresden corridor caused 4G/5G data outage affecting 260,000 subscribers. Oliver Schmidt executed emergency route re-injection and validated end-to-end data connectivity.",
    tags: ["4G Data", "5G NR", "BGP", "Leipzig", "Dresden"],
    evidence: ["BGP route withdrawn: LPZ-GW-03", "Subscriber impact: 260,000", "Firmware push at 13:00 UTC identified as root cause"],
    timeline: [
      { time: "13:15", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "13:22", event: "Assigned to Oliver Schmidt", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "14:10", event: "Root cause: firmware push at 13:00", actor: "Oliver Schmidt", color: "#E2008A", badge: "Root Cause", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "16:30", event: "Resolved — route re-injected", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1959",
    title: "Roaming Certificate Pre-Expiry — T-Mobile PL",
    service: "Roaming",
    sev: "Minor",
    status: "Resolved",
    date: "2026-02-04",
    time: "15:00",
    endDate: "2026-02-04",
    resolvedAt: "15:50",
    duration: "0h 50m",
    assigned: "Kai Fischer",
    classification: "Certificate Expiry",
    score: "2.4",
    sparkTrend: [1, 1, 2, 2, 2, 2, 1, 1],
    summary: "48-hour pre-expiry warning for T-Mobile PL roaming certificate. Kai Fischer renewed the certificate proactively with no service impact.",
    tags: ["Roaming", "DEA", "X.509", "T-Mobile PL"],
    evidence: ["DEA cert expiry: 48h remaining", "T-Mobile PL interconnect affected"],
    timeline: [
      { time: "15:00", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "15:50", event: "Resolved — certificate renewed", actor: "Kai Fischer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1961",
    title: "IMS Core Congestion — Peak Hours",
    service: "Core/IMS",
    sev: "Major",
    status: "Resolved",
    date: "2026-02-06",
    time: "10:00",
    endDate: "2026-02-06",
    resolvedAt: "12:30",
    duration: "2h 30m",
    assigned: "Stefan Bauer",
    classification: "Network Congestion",
    score: "5.3",
    sparkTrend: [2, 3, 5, 6, 6, 5, 4, 2],
    summary: "IMS core experienced network congestion during morning peak hours due to a lack of traffic shaping on bulk OTT call traffic. Stefan Bauer implemented dynamic QoS policies to relieve the congestion.",
    tags: ["IMS", "Core", "QoS", "Congestion", "OTT"],
    evidence: ["IMS CPU: 91%", "SIP transaction rate 3× baseline", "OTT bulk traffic unclassified"],
    timeline: [
      { time: "10:00", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "10:15", event: "Assigned to Stefan Bauer", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "12:30", event: "Resolved — QoS policies applied", actor: "Stefan Bauer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1963",
    title: "VoLTE Hardware Fault — Cologne Node 3",
    service: "Voice",
    sev: "Critical",
    status: "Resolved",
    date: "2026-02-10",
    time: "09:30",
    endDate: "2026-02-10",
    resolvedAt: "14:30",
    duration: "5h 00m",
    assigned: "Jacob Meyer",
    classification: "Hardware Fault",
    score: "8.7",
    sparkTrend: [3, 5, 8, 9, 10, 9, 7, 4],
    summary: "VoLTE media gateway Node 3 in Cologne suffered a backplane switch failure causing loss of 28% of regional voice capacity. Jacob Meyer coordinated emergency hardware replacement and traffic redistribution.",
    tags: ["VoLTE", "Voice", "Cologne", "Backplane", "Hardware"],
    evidence: ["Backplane failure: COL-MGW-03", "Voice capacity loss: 28%", "Emergency services rerouted"],
    timeline: [
      { time: "09:30", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "09:38", event: "Assigned to Jacob Meyer", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "11:00", event: "Traffic redistribution complete", actor: "Jacob Meyer", color: "#E2008A", badge: "Mitigation", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "14:30", event: "Resolved — backplane replaced", actor: "Jacob Meyer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1965",
    title: "SMSC Config Rollback Failure — Bonn",
    service: "SMS",
    sev: "Major",
    status: "Resolved",
    date: "2026-02-10",
    time: "12:00",
    endDate: "2026-02-10",
    resolvedAt: "14:30",
    duration: "2h 30m",
    assigned: "Anna Weber",
    classification: "Config Error",
    score: "5.6",
    sparkTrend: [2, 3, 5, 6, 6, 5, 3, 2],
    summary: "SMSC config rollback in Bonn failed due to a locked config file, leaving the cluster in a partially inconsistent state. Anna Weber manually corrected the config and released the lock.",
    tags: ["SMSC", "Bonn", "Config Rollback", "Config Lock"],
    evidence: ["Config lock file found on SMSC-BON-01", "Delivery failure rate: 12%"],
    timeline: [
      { time: "12:00", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "12:14", event: "Assigned to Anna Weber", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "14:30", event: "Resolved — config lock released", actor: "Anna Weber", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1967",
    title: "5G NR Firmware Regression — Hannover",
    service: "5G NR",
    sev: "Major",
    status: "Resolved",
    date: "2026-02-11",
    time: "10:30",
    endDate: "2026-02-11",
    resolvedAt: "13:00",
    duration: "2h 30m",
    assigned: "Lena Hoffmann",
    classification: "Firmware Bug",
    score: "5.5",
    sparkTrend: [1, 2, 4, 5, 6, 5, 4, 2],
    summary: "gNB firmware v3.9.1 introduced a MIMO layer mapping regression across the Hannover cluster, reducing downlink throughput by 44%. Lena Hoffmann rolled back to v3.8.3.",
    tags: ["5G NR", "gNB", "MIMO", "Hannover", "Firmware"],
    evidence: ["Downlink throughput: -44%", "MIMO layer mapping error in v3.9.1"],
    timeline: [
      { time: "10:30", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "10:44", event: "Assigned to Lena Hoffmann", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "13:00", event: "Resolved — rolled back to v3.8.3", actor: "Lena Hoffmann", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1969",
    title: "IoT Registration DNS Failure — Frankfurt APN",
    service: "IoT/M2M",
    sev: "Minor",
    status: "Resolved",
    date: "2026-02-12",
    time: "09:15",
    endDate: "2026-02-12",
    resolvedAt: "10:00",
    duration: "0h 45m",
    assigned: "Stefan Bauer",
    classification: "DNS Issue",
    score: "2.4",
    sparkTrend: [1, 1, 2, 2, 2, 2, 1, 1],
    summary: "DNS failure on the Frankfurt IoT APN caused device registration failures for ~4,200 IoT devices. Stefan Bauer restarted the affected resolver and validated recovery.",
    tags: ["IoT", "M2M", "DNS", "Frankfurt APN"],
    evidence: ["DNS resolver failure: FRA-APN-DNS-02", "IoT registration failures: 4,200 devices"],
    timeline: [
      { time: "09:15", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "10:00", event: "Resolved — resolver restarted", actor: "Stefan Bauer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1971",
    title: "4G/5G Data Outage — Frankfurt Region",
    service: "4G/5G Data",
    sev: "Critical",
    status: "Resolved",
    date: "2026-02-13",
    time: "11:45",
    endDate: "2026-02-13",
    resolvedAt: "16:15",
    duration: "4h 30m",
    assigned: "Oliver Schmidt",
    classification: "BGP Failure",
    score: "9.1",
    sparkTrend: [4, 6, 8, 10, 10, 9, 7, 4],
    summary: "BGP route withdrawal on the Frankfurt region backbone caused a major 4G/5G data outage affecting 320,000 subscribers. Root cause traced to a misconfigured firewall rule pushed during a change window at 11:30 UTC. Oliver Schmidt coordinated the rollback and validated full service restoration.",
    tags: ["4G Data", "5G NR", "BGP", "Frankfurt", "Firewall"],
    evidence: ["BGP session drop: FRA-BB-01", "Subscriber impact: 320,000", "Firewall rule change: 11:30 UTC"],
    timeline: [
      { time: "11:45", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "11:53", event: "Assigned to Oliver Schmidt", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "12:40", event: "Root cause: firewall rule at 11:30", actor: "Oliver Schmidt", color: "#E2008A", badge: "Root Cause", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "16:15", event: "Resolved — firewall rule rolled back", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1973",
    title: "Roaming Certificate Expiry — Vodafone IT",
    service: "Roaming",
    sev: "Major",
    status: "Resolved",
    date: "2026-02-14",
    time: "13:00",
    endDate: "2026-02-14",
    resolvedAt: "15:30",
    duration: "2h 30m",
    assigned: "Kai Fischer",
    classification: "Certificate Expiry",
    score: "6.1",
    sparkTrend: [2, 3, 5, 6, 6, 5, 4, 2],
    summary: "DEA certificate for Vodafone IT interconnect expired causing auth failures for Italian roamers. Auto-renewal failed due to an expired API token in the renewal system. Kai Fischer manually renewed the certificate and fixed the renewal token.",
    tags: ["Roaming", "DEA", "X.509", "Vodafone IT", "Auto-renewal"],
    evidence: ["DEA cert expired: DEA-VIT-01", "Auth failure: 71% for Vodafone IT subscribers", "Auto-renewal API token expired"],
    timeline: [
      { time: "13:00", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "13:14", event: "Assigned to Kai Fischer", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "13:55", event: "Root cause: expired renewal API token", actor: "Kai Fischer", color: "#E2008A", badge: "Root Cause", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "15:30", event: "Resolved — cert renewed, token fixed", actor: "Kai Fischer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1975",
    title: "Voice QoS Congestion — Munich Evening Peak",
    service: "Voice",
    sev: "Minor",
    status: "Resolved",
    date: "2026-02-14",
    time: "16:30",
    endDate: "2026-02-14",
    resolvedAt: "17:15",
    duration: "0h 45m",
    assigned: "Mia Becker",
    classification: "Network Congestion",
    score: "2.7",
    sparkTrend: [1, 1, 2, 3, 3, 2, 2, 1],
    summary: "Brief voice quality degradation during the Munich evening peak due to QoS queue saturation. Mia Becker adjusted the voice traffic priority queue and congestion cleared.",
    tags: ["Voice", "QoS", "Munich", "Evening Peak"],
    evidence: ["Voice MOS score: 2.9 (threshold: 3.5)", "QoS queue saturation: VOX-MUC-01"],
    timeline: [
      { time: "16:30", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "17:15", event: "Resolved — QoS queue adjusted", actor: "Mia Becker", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1977",
    title: "IMS Core Software Bug — Signalling Loop",
    service: "Core/IMS",
    sev: "Critical",
    status: "Resolved",
    date: "2026-02-17",
    time: "10:15",
    endDate: "2026-02-17",
    resolvedAt: "17:45",
    duration: "7h 30m",
    assigned: "Oliver Schmidt",
    classification: "Software Bug",
    score: "9.5",
    sparkTrend: [4, 6, 8, 10, 10, 10, 8, 5],
    summary: "A software defect in IMS release 4.12 caused a SIP re-INVITE processing loop under high load conditions, escalating CPU utilisation to 100% on all IMS processing nodes. Oliver Schmidt coordinated an emergency patch deployment and controlled service restart sequence.",
    tags: ["IMS", "SIP", "re-INVITE", "Software Bug", "CPU", "Core"],
    evidence: ["IMS CPU: 100% all nodes", "SIP re-INVITE loop detected", "Vendor emergency patch requested", "CTO, CEO notified"],
    timeline: [
      { time: "10:15", event: "Detection", actor: "AI Agent", color: "#ff3b5c", badge: "Detection", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "10:22", event: "Assigned to Oliver Schmidt", actor: "Critical SLA Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "11:00", event: "CTO/CEO notified", actor: "Oliver Schmidt", color: "#ff3b5c", badge: "Escalation", badgeBg: "rgba(255,59,92,0.15)" },
      { time: "13:30", event: "Vendor emergency patch received", actor: "Vendor NOC", color: "#E2008A", badge: "Mitigation", badgeBg: "rgba(226,0,138,0.15)" },
      { time: "17:45", event: "Resolved — patch deployed, service restored", actor: "Oliver Schmidt", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1979",
    title: "4G GGSN Capacity Breach — Cologne Metro",
    service: "4G/5G Data",
    sev: "Major",
    status: "Resolved",
    date: "2026-02-18",
    time: "09:30",
    endDate: "2026-02-18",
    resolvedAt: "12:00",
    duration: "2h 30m",
    assigned: "Mia Becker",
    classification: "Capacity Breach",
    score: "5.8",
    sparkTrend: [2, 3, 5, 6, 7, 5, 4, 2],
    summary: "GGSN pool capacity in Cologne Metro was breached by sustained high-traffic demand following a major sporting event. Mia Becker provisioned additional GGSN nodes and load-balanced the pool.",
    tags: ["4G", "GGSN", "Capacity", "Cologne Metro"],
    evidence: ["GGSN pool utilisation: 96%", "Traffic sustained above baseline for 4h"],
    timeline: [
      { time: "09:30", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "09:44", event: "Assigned to Mia Becker", actor: "Auto-assignment", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "12:00", event: "Resolved — capacity expanded", actor: "Mia Becker", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1981",
    title: "VoLTE Config Drift — IMS Media Plane",
    service: "Voice",
    sev: "Major",
    status: "Resolved",
    date: "2026-02-19",
    time: "11:00",
    endDate: "2026-02-19",
    resolvedAt: "13:30",
    duration: "2h 30m",
    assigned: "Jacob Meyer",
    classification: "Config Error",
    score: "5.4",
    sparkTrend: [2, 3, 4, 5, 6, 5, 3, 2],
    summary: "Configuration drift on the IMS media plane caused elevated RTP packet loss (6.8%) for a subset of VoLTE calls. Jacob Meyer identified the drift via config auditing and pushed the corrected baseline.",
    tags: ["VoLTE", "IMS", "RTP", "Config Drift", "Media Plane"],
    evidence: ["RTP packet loss: 6.8% vs 0.5% baseline", "Config drift on IMS-MP-FRA-02"],
    timeline: [
      { time: "11:00", event: "Detection", actor: "AI Agent", color: "#ff8c00", badge: "Detection", badgeBg: "rgba(255,140,0,0.15)" },
      { time: "11:15", event: "Assigned to Jacob Meyer", actor: "NOC Shift Lead", color: "#38bdf8", badge: "Assignment", badgeBg: "rgba(56,189,248,0.15)" },
      { time: "13:30", event: "Resolved — config baseline restored", actor: "Jacob Meyer", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
  {
    id: "INC-1983",
    title: "SMSC DNS Resolver Restart — Munich",
    service: "SMS",
    sev: "Minor",
    status: "Resolved",
    date: "2026-02-20",
    time: "14:30",
    endDate: "2026-02-20",
    resolvedAt: "15:15",
    duration: "0h 45m",
    assigned: "Anna Weber",
    classification: "DNS Issue",
    score: "2.0",
    sparkTrend: [1, 1, 1, 2, 2, 2, 1, 1],
    summary: "SMSC DNS resolver in Munich required a restart following memory exhaustion. Anna Weber restarted the resolver and applied a memory limit patch.",
    tags: ["SMSC", "DNS", "Munich", "Memory"],
    evidence: ["DNS resolver memory: 99.8%", "SMSC-MUC-DNS-01 restart required"],
    timeline: [
      { time: "14:30", event: "Detection", actor: "AI Agent", color: "#f5c518", badge: "Detection", badgeBg: "rgba(245,197,24,0.15)" },
      { time: "15:15", event: "Resolved — resolver restarted + patched", actor: "Anna Weber", color: "#00c896", badge: "Resolved", badgeBg: "rgba(0,200,150,0.15)" },
    ],
  },
];

export const HISTORY_ENGINEERS = [
  "Oliver Schmidt",
  "Jacob Meyer",
  "Anna Weber",
  "Stefan Bauer",
  "Lena Hoffmann",
  "Kai Fischer",
  "Mia Becker",
];

export const HISTORY_SERVICES = [
  "4G/5G Data",
  "Voice",
  "SMS",
  "Roaming",
  "IoT/M2M",
  "Core/IMS",
  "5G NR",
];

export const HISTORY_CLASSIFICATIONS = [
  "BGP Failure",
  "Config Error",
  "Hardware Fault",
  "Capacity Breach",
  "Certificate Expiry",
  "DNS Issue",
  "Software Bug",
  "Firmware Bug",
  "Network Congestion",
  "Maintenance Window",
];
